package dev.practice.assessment03.contract;
import dev.practice.assessment03.support.ApiTestSupport;import dev.practice.assessment03.support.Fixtures;import java.util.*;import com.fasterxml.jackson.databind.node.ObjectNode;import org.junit.jupiter.api.*;import static org.assertj.core.api.Assertions.assertThat;
public class ReservationPublicContractTest extends ApiTestSupport {
 @Test @DisplayName("Create response and protected fields") void a3_01() throws Exception { var r=req("POST","/api/reservations",standard("req-001").put("id",777).put("status","CANCELLED").put("totalQuantity",999));assertThat(r.getResponse().getStatus()).isEqualTo(201);var n=json(r);long id=n.path("id").asLong();assertThat(id).isPositive().isNotEqualTo(777);assertThat(r.getResponse().getHeader("Location")).isEqualTo("/api/reservations/"+id);response(n,id,"req-001","team-a","ACTIVE","BOLT-M8=3","NUT-M8=2");assertThat(n.path("totalQuantity").asInt()).isEqualTo(5); }
 @Test @DisplayName("Committed creation workflow") void a3_02() throws Exception { var n=create(standard("req-001"),201);long id=n.path("id").asLong();stocks(7,6);counts(1,2,1);stored(id,"req-001","team-a","ACTIVE");persistedLines(id,"BOLT-M8=3","NUT-M8=2");events(id,"CREATED"); }
 @Test @DisplayName("Unknown stock rolls back") void a3_03() throws Exception { var before=snapshot();error("POST","/api/reservations",request("req-unknown",item("UNKNOWN-1",1)),404,"STOCK_NOT_FOUND");assertThat(snapshot()).isEqualTo(before);counts(0,0,0); }
 @Test @DisplayName("Insufficient stock rolls back") void a3_04() throws Exception { var before=snapshot();error("POST","/api/reservations",request("req-short",item("BOLT-M8",11)),409,"INSUFFICIENT_STOCK");assertThat(snapshot()).isEqualTo(before);counts(0,0,0); }
 @Test @DisplayName("Exact stock depletion") void a3_05() throws Exception { var n=create(request("req-exact",item("BOLT-M8",10)),201);stock("BOLT-M8",0);counts(1,1,1);persistedLines(n.path("id").asLong(),"BOLT-M8=10");events(n.path("id").asLong(),"CREATED"); }
 @Test @DisplayName("Invalid requests never write") void a3_06() throws Exception { var bad=new ArrayList<Object>();for(String f:List.of("requestKey","customerRef","items")){var b=standard("valid");b.remove(f);bad.add(b);bad.add(standard("valid").putNull(f));}bad.addAll(List.of(standard(" "),standard("x".repeat(65)),standard("bad key"),standard("valid").put("customerRef"," "),standard("valid").put("customerRef","x".repeat(65))));var empty=standard("valid");empty.putArray("items");bad.add(empty);var many=standard("valid");var a=many.putArray("items");for(int i=0;i<21;i++)a.add(item("BOLT-M8",1));bad.add(many);var nullItem=standard("valid");nullItem.putArray("items").addNull();bad.add(nullItem);for(String f:List.of("sku","quantity")){var i=item("BOLT-M8",1);i.remove(f);bad.add(request("valid",i));bad.add(request("valid",item("BOLT-M8",1).putNull(f)));}for(String sku:List.of(" ","BAD_SKU","X".repeat(33)))bad.add(request("valid",item(sku,1)));for(int q:List.of(0,101))bad.add(request("valid",item("BOLT-M8",q)));bad.add(request("valid",item("BOLT-M8",1).put("quantity",1.5)));bad.add("{\"requestKey\":\"abc\"");for(Object b:bad){reset();var before=snapshot();error("POST","/api/reservations",b,400,"INVALID_REQUEST");assertThat(snapshot()).isEqualTo(before);} }
 @Test @DisplayName("Duplicate items merge") void a3_07() throws Exception { var n=create(request("req-merge",item("BOLT-M8",1),item("BOLT-M8",2)),201);long id=n.path("id").asLong();response(n,id,"req-merge","team-a","ACTIVE","BOLT-M8=3");stock("BOLT-M8",7);counts(1,1,1);persistedLines(id,"BOLT-M8=3");events(id,"CREATED"); }
 @Test @DisplayName("Read committed reservation") void a3_08() throws Exception { Fixtures.active701(jdbc);var before=snapshot();response(ok("GET","/api/reservations/701",null,200),701,"fixture-701","team-a","ACTIVE","BOLT-M8=3","NUT-M8=2");assertThat(snapshot()).isEqualTo(before); }
 @Test @DisplayName("Missing and invalid lookup IDs") void a3_09() throws Exception { var before=snapshot();error("GET","/api/reservations/9999",null,404,"RESERVATION_NOT_FOUND");for(String id:List.of("0","-1","abc"))error("GET","/api/reservations/"+id,null,400,"INVALID_REQUEST");assertThat(snapshot()).isEqualTo(before); }
 @Test @DisplayName("Identical replay is read only") void a3_10() throws Exception { var a=create(standard("req-001"),201);var before=snapshot();var b=create(standard("req-001"),200);assertThat(b).isEqualTo(a);assertThat(snapshot()).isEqualTo(before);stocks(7,6);counts(1,2,1);events(a.path("id").asLong(),"CREATED"); }
 @Test @DisplayName("Changed lines conflict") void a3_11() throws Exception { create(request("req-001",item("BOLT-M8",3)),201);var before=snapshot();error("POST","/api/reservations",request("req-001",item("BOLT-M8",4)),409,"IDEMPOTENCY_CONFLICT");assertThat(snapshot()).isEqualTo(before); }
 @Test @DisplayName("Cancel restores inventory") void a3_12() throws Exception { Fixtures.active701(jdbc);var n=cancel(701,200);response(n,701,"fixture-701","team-a","CANCELLED","BOLT-M8=3","NUT-M8=2");stocks(10,8);counts(1,2,2);persistedLines(701,"BOLT-M8=3","NUT-M8=2");events(701,"CANCELLED","CREATED");assertThat(jdbc.queryForObject("select status from reservations where id=701",String.class)).isEqualTo("CANCELLED"); }
 @Test @DisplayName("Repeated cancellation is read only") void a3_13() throws Exception { Fixtures.active701(jdbc);var a=cancel(701,200);response(a,701,"fixture-701","team-a","CANCELLED","BOLT-M8=3","NUT-M8=2");var before=snapshot();assertThat(cancel(701,200)).isEqualTo(a);assertThat(snapshot()).isEqualTo(before);stocks(10,8);counts(1,2,2);events(701,"CANCELLED","CREATED"); }
 @Test @DisplayName("Later line failure rolls back") void a3_14() throws Exception { var before=snapshot();error("POST","/api/reservations",request("req-rollback",item("BOLT-M8",3),item("WASHER-M8",1)),409,"INSUFFICIENT_STOCK");assertThat(snapshot()).isEqualTo(before);stocks(10,8);counts(0,0,0);assertThat(jdbc.queryForObject("select count(*) from reservations where request_key='req-rollback'",Integer.class)).isZero(); }
 @Test @DisplayName("Initial complete inventory summary") void a3_15() throws Exception { summary(ok("GET","/api/inventory/summary",null,200),new int[]{10,20,8,0},new long[]{0,0,0,0},new long[]{0,0,0,0}); }
}
