package dev.practice.assessment03.contract;
import dev.practice.assessment03.support.ApiTestSupport;import dev.practice.assessment03.support.Fixtures;import java.util.*;import com.fasterxml.jackson.databind.node.ObjectNode;import org.junit.jupiter.api.*;import static org.assertj.core.api.Assertions.assertThat;
public class ReservationPrivateContractTest extends ApiTestSupport {
 @Test @DisplayName("Normalized equivalent requests replay") void a3_16() throws Exception { var n=create(request(" req-normal ",item(" bolt-m8 ",1),item(" nut-m8 ",2),item("BOLT-M8",2)).put("customerRef"," team-a "),201);long id=n.path("id").asLong();response(n,id,"req-normal","team-a","ACTIVE","BOLT-M8=3","NUT-M8=2");stocks(7,6);assertThat(create(request("req-normal",item("NUT-M8",2),item("BOLT-M8",3)),200)).isEqualTo(n);counts(1,2,1);events(id,"CREATED"); }
 @Test @DisplayName("Different customer conflicts") void a3_17() throws Exception { create(request("shared-key",item("BOLT-M8",2)),201);var before=snapshot();error("POST","/api/reservations",request("shared-key",item("BOLT-M8",2)).put("customerRef","team-b"),409,"IDEMPOTENCY_CONFLICT");assertThat(snapshot()).isEqualTo(before); }
 @Test @DisplayName("Business failure leaves key reusable") void a3_18() throws Exception { var b=request("retry-stock",item("WASHER-M8",1));error("POST","/api/reservations",b,409,"INSUFFICIENT_STOCK");counts(0,0,0);stocks(10,8);jdbc.update("update stock_items set available_quantity=3 where sku='WASHER-M8'");var n=create(b,201);stock("WASHER-M8",2);counts(1,1,1);events(n.path("id").asLong(),"CREATED"); }
 @Test @DisplayName("Creation audit failure rolls back and retries") void a3_19() throws Exception { var before=snapshot();audit.failNextCreated();error("POST","/api/reservations",standard("audit-retry"),503,"RESERVATION_UNAVAILABLE");assertThat(snapshot()).isEqualTo(before);counts(0,0,0);stocks(10,8);var n=create(standard("audit-retry"),201);stocks(7,6);counts(1,2,1);persistedLines(n.path("id").asLong(),"BOLT-M8=3","NUT-M8=2");events(n.path("id").asLong(),"CREATED"); }
 @Test @DisplayName("Cancellation audit failure rolls back and retries") void a3_20() throws Exception { Fixtures.active701(jdbc);var before=snapshot();audit.failNextCancelled();error("POST","/api/reservations/701/cancel",null,503,"RESERVATION_UNAVAILABLE");assertThat(snapshot()).isEqualTo(before);stocks(7,6);assertThat(jdbc.queryForObject("select status from reservations where id=701",String.class)).isEqualTo("ACTIVE");var n=cancel(701,200);assertThat(n.path("status").asText()).isEqualTo("CANCELLED");stocks(10,8);counts(1,2,2);events(701,"CANCELLED","CREATED"); }
 @Test @DisplayName("Merged quantity uses stock limit") void a3_21() throws Exception { var before=snapshot();error("POST","/api/reservations",request("merged-short",item("BOLT-M8",6),item("BOLT-M8",5)),409,"INSUFFICIENT_STOCK");assertThat(snapshot()).isEqualTo(before);counts(0,0,0); }
 @Test @DisplayName("Summary aggregates active reservations only") void a3_22() throws Exception { Fixtures.active701(jdbc);Fixtures.reservation(jdbc,702,"fixture-702","team-b","ACTIVE","[\"team-b\",[[\"BOLT-M8\",2]]]");Fixtures.line(jdbc,713,702,"BOLT-M8",2);Fixtures.event(jdbc,723,702,"CREATED");Fixtures.reservation(jdbc,703,"fixture-703","team-c","CANCELLED","[\"team-c\",[[\"BOLT-M8\",4]]]");Fixtures.line(jdbc,714,703,"BOLT-M8",4);Fixtures.event(jdbc,724,703,"CREATED");Fixtures.event(jdbc,725,703,"CANCELLED");jdbc.update("update stock_items set available_quantity=5 where sku='BOLT-M8'");summary(ok("GET","/api/inventory/summary",null,200),new int[]{5,20,6,0},new long[]{5,0,2,0},new long[]{2,0,1,0}); }
 @Test @DisplayName("Missing and invalid cancellation IDs") void a3_23() throws Exception { Fixtures.active701(jdbc);var before=snapshot();error("POST","/api/reservations/9999/cancel",null,404,"RESERVATION_NOT_FOUND");for(String id:List.of("0","-1","abc"))error("POST","/api/reservations/"+id+"/cancel",null,400,"INVALID_REQUEST");assertThat(snapshot()).isEqualTo(before); }
 @Test @DisplayName("Request keys retain case") void a3_24() throws Exception { var a=create(request(" r-Key ",item("BOLT-M8",2)),201);assertThat(a.path("requestKey").asText()).isEqualTo("r-Key");assertThat(create(request("r-Key",item("BOLT-M8",2)),200)).isEqualTo(a);var b=create(request("R-Key",item("BOLT-M8",2)),201);assertThat(b.path("id").asLong()).isNotEqualTo(a.path("id").asLong());counts(2,2,2);stock("BOLT-M8",6);events(a.path("id").asLong(),"CREATED");events(b.path("id").asLong(),"CREATED"); }
 @Test @DisplayName("Cancelled replay does not check stock") void a3_25() throws Exception { for(boolean depleted:List.of(false,true)){reset();var original=create(standard("cancelled-replay"),201);long id=original.path("id").asLong();cancel(id,200);if(depleted)jdbc.update("update stock_items set available_quantity=0 where sku in ('BOLT-M8','NUT-M8')");var before=snapshot();var n=create(standard("cancelled-replay"),200);response(n,id,"cancelled-replay","team-a","CANCELLED","BOLT-M8=3","NUT-M8=2");assertThat(snapshot()).isEqualTo(before);counts(1,2,2);events(id,"CANCELLED","CREATED");} }
}
