package dev.practice.assessment01.contract;
import dev.practice.assessment01.support.ApiTestSupport;
import java.util.*;
import org.junit.jupiter.api.*;
import static org.assertj.core.api.Assertions.assertThat;
public class TicketPrivateContractTest extends ApiTestSupport {
 @Test @DisplayName("Required create fields") void a1_16() throws Exception { var before=snapshot();for(String f:List.of("externalRef","title","priority")){var b=create("INC-200");b.remove(f);error("POST","/api/tickets",b,400,"INVALID_REQUEST");b=create("INC-200");b.putNull(f);error("POST","/api/tickets",b,400,"INVALID_REQUEST");assertThat(snapshot()).isEqualTo(before);} }
 @Test @DisplayName("Normalized title limits") void a1_17() throws Exception { var n=ok("POST","/api/tickets",create("INC-200").put("title","  "+"x".repeat(120)+"  "),201);stored(n.path("id").asLong(),"INC-200","x".repeat(120),2,"OPEN");var before=snapshot();error("POST","/api/tickets",create("INC-201").put("title","x".repeat(121)),400,"INVALID_REQUEST");assertThat(snapshot()).isEqualTo(before); }
 @Test @DisplayName("Normalized uniqueness") void a1_18() throws Exception { var before=snapshot();error("POST","/api/tickets",create("  inc-101  "),409,"DUPLICATE_REFERENCE");assertThat(snapshot()).isEqualTo(before); }
 @Test @DisplayName("Reference boundaries") void a1_19() throws Exception { for(String ref:List.of("A-1","A".repeat(32))){reset();var n=ok("POST","/api/tickets",create(ref),201);stored(n.path("id").asLong(),ref,"New incident",2,"OPEN");count(5);}for(String ref:List.of("A1","A".repeat(33),"INC_200")){reset();error("POST","/api/tickets",create(ref),400,"INVALID_REQUEST");count(4);} }
 @Test @DisplayName("Immutable update fields") void a1_20() throws Exception { var n=ok("PUT","/api/tickets/101",update().put("title"," Edited title ").put("id",888).put("externalRef","REPLACED"),200);ticket(n,101,"INC-101","Edited title",4,"OPEN");stored(101,"INC-101","Edited title",4,"OPEN");assertThat(jdbc.queryForObject("select count(*) from tickets where id=888 or external_ref='REPLACED'",Integer.class)).isZero();count(4); }
 @Test @DisplayName("Invalid replacement preserves data") void a1_21() throws Exception { var before=snapshot();var absent=update();absent.remove("status");for(var b:List.of(update().put("status","UNKNOWN"),update().put("status"," "),update().putNull("status"),absent,update().put("priority",-1),update().put("title"," "))){error("PUT","/api/tickets/101",b,400,"INVALID_REQUEST");assertThat(snapshot()).isEqualTo(before);} }
 @Test @DisplayName("Normalized and invalid status query") void a1_22() throws Exception { assertThat(ids(ok("GET","/api/tickets?status= open ",null,200))).containsExactly(101L,103L);for(String q:List.of("UNKNOWN"," "))error("GET","/api/tickets?status="+q,null,400,"INVALID_REQUEST"); }
 @Test @DisplayName("Invalid sort and path IDs") void a1_23() throws Exception { var before=snapshot();for(String q:List.of("unknown",""))error("GET","/api/tickets?sort="+q,null,400,"INVALID_REQUEST");for(String id:List.of("0","-1","abc")){error("GET","/api/tickets/"+id,null,400,"INVALID_REQUEST");error("PUT","/api/tickets/"+id,update(),400,"INVALID_REQUEST");error("DELETE","/api/tickets/"+id,null,400,"INVALID_REQUEST");}assertThat(snapshot()).isEqualTo(before); }
 @Test @DisplayName("Empty filtered and empty collection") void a1_24() throws Exception { jdbc.update("update tickets set status='RESOLVED'");var filtered=ok("GET","/api/tickets?status=OPEN",null,200);assertThat(filtered.isArray()).isTrue();assertThat(filtered.isEmpty()).isTrue();jdbc.update("delete from tickets");var empty=ok("GET","/api/tickets",null,200);assertThat(empty.isArray()).isTrue();assertThat(empty.isEmpty()).isTrue(); }
 @Test @DisplayName("Reference can be reused after deletion") void a1_25() throws Exception { assertThat(req("DELETE","/api/tickets/101",null).getResponse().getStatus()).isEqualTo(204);var n=ok("POST","/api/tickets",create("inc-101"),201);assertThat(n.path("id").asLong()).isNotEqualTo(101);assertThat(n.path("externalRef").asText()).isEqualTo("INC-101");count(4);assertThat(jdbc.queryForObject("select count(*) from tickets where id=101",Integer.class)).isZero(); }
}
