package dev.practice.assessment02.contract;
import dev.practice.assessment02.support.ApiTestSupport;import java.util.*;import com.fasterxml.jackson.databind.node.ObjectNode;import org.junit.jupiter.api.*;import static org.assertj.core.api.Assertions.assertThat;
public class CatalogPublicContractTest extends ApiTestSupport {
 @Test @DisplayName("Default page shape and totals") void a2_01() throws Exception { var n=search("");content(n,107L,112L,105L,106L,110L);metadata(n,0,5,12,3,true,false);n.path("content").forEach(x->shape(x,"id","sku","name","category","priceCents","stock")); }
 @Test @DisplayName("Combined name and category filters") void a2_02() throws Exception { content(search("q=keyboard&category=accessories&size=50"),112L); }
 @Test @DisplayName("Blank and unknown filters") void a2_03() throws Exception { content(search("q=   &category=   &size=50"),107L,112L,105L,106L,110L,103L,104L,101L,111L,102L,109L,108L);cacheReset();content(search("category=hardware")); }
 @Test @DisplayName("Normalized search text") void a2_04() throws Exception { content(search("q= MOUSE &category= ELECTRONICS &size=50"),103L,104L); }
 @Test @DisplayName("Inclusive price bounds") void a2_05() throws Exception { content(search("minPrice=2500&maxPrice=5000&size=50"),103L,104L,101L,111L); }
 @Test @DisplayName("Stock predicates") void a2_06() throws Exception { content(search("category=electronics&inStock=true&size=50"),110L,103L,104L,101L);cacheReset();content(search("category=electronics&inStock=false&size=50"),102L); }
 @Test @DisplayName("Second page and metadata") void a2_07() throws Exception { var n=search("category=electronics&page=1&size=2");content(n,104L,101L);metadata(n,1,2,5,3,false,false); }
 @Test @DisplayName("Descending price ties") void a2_08() throws Exception { content(search("category=electronics&sort=priceDesc&size=50"),102L,101L,103L,104L,110L); }
 @Test @DisplayName("Name ordering") void a2_09() throws Exception { content(search("category=electronics&sort=nameAsc&size=50"),101L,102L,104L,110L,103L); }
 @Test @DisplayName("Out of range page") void a2_10() throws Exception { var n=search("category=furniture&page=9&size=2");content(n);metadata(n,9,2,3,2,false,true); }
 @Test @DisplayName("Empty search page") void a2_11() throws Exception { var n=search("q=volcano");content(n);metadata(n,0,5,0,0,true,true); }
 @Test @DisplayName("Invalid searches have no effects") void a2_12() throws Exception { var queries=new ArrayList<>(List.of("page=-1","page=1000001","page=abc","size=0","size=51","minPrice=-1","maxPrice=1000000001","minPrice=5001&maxPrice=5000","inStock=maybe","sort=unknown","q="+"x".repeat(81),"category="+"x".repeat(41)));for(String key:List.of("page","size","minPrice","maxPrice","inStock","sort"))queries.add(key+"=");for(String q:queries){error("GET","/api/products?"+q,null,400,"INVALID_REQUEST");calls(0);assertThat(cache.keys()).isEmpty();} }
 @Test @DisplayName("Cache reuses populated and empty responses") void a2_13() throws Exception { var a=search("category=electronics&size=50");content(a,110L,103L,104L,101L,102L);assertThat(search("category=electronics&size=50")).isEqualTo(a);calls(1);reset();var b=search("q=volcano");content(b);assertThat(search("q=volcano")).isEqualTo(b);calls(1); }
 @Test @DisplayName("Successful writes refresh searches") void a2_14() throws Exception { content(search("category=electronics&size=50"),110L,103L,104L,101L,102L);content(search("category=accessories&size=50"),112L);calls(2);var n=ok("PUT","/api/products/103",update().put("name"," Wireless Mouse ").put("category"," Accessories ").put("priceCents",3000).put("stock",0).put("id",888).put("sku","HACKED"),200);shape(n,"id","sku","name","category","priceCents","stock");assertThat(n.path("id").asLong()).isEqualTo(103);assertThat(n.path("sku").asText()).isEqualTo("MS-01");assertThat(n.path("name").asText()).isEqualTo("Wireless Mouse");assertThat(n.path("category").asText()).isEqualTo("accessories");assertThat(n.path("priceCents").asInt()).isEqualTo(3000);assertThat(n.path("stock").asInt()).isZero();var row=jdbc.queryForMap("select * from products where id=103");assertThat(row.get("SKU")).isEqualTo("MS-01");assertThat(row.get("NAME")).isEqualTo("Wireless Mouse");assertThat(row.get("CATEGORY")).isEqualTo("accessories");assertThat(((Number)row.get("PRICE_CENTS")).intValue()).isEqualTo(3000);assertThat(((Number)row.get("STOCK")).intValue()).isZero();content(search("category=electronics&size=50"),110L,104L,101L,102L);content(search("category=accessories&size=50"),112L,103L);calls(4); }
 @Test @DisplayName("Failed writes preserve cache and rows") void a2_15() throws Exception { var before=snapshot();var n=search("category=electronics&size=50");content(n,110L,103L,104L,101L,102L);calls(1);error("PUT","/api/products/9999",update(),404,"NOT_FOUND");error("PUT","/api/products/103",update().put("stock",-1),400,"INVALID_REQUEST");assertThat(snapshot()).isEqualTo(before);assertThat(search("category=electronics&size=50")).isEqualTo(n);calls(1); }
}
