package dev.practice.assessment02.contract;
import dev.practice.assessment02.support.ApiTestSupport;import java.util.*;import com.fasterxml.jackson.databind.node.ObjectNode;import org.junit.jupiter.api.*;import static org.assertj.core.api.Assertions.assertThat;
public class CatalogPrivateContractTest extends ApiTestSupport {
 @Test @DisplayName("Page and size cache separation") void a2_16() throws Exception { String[] qs={"category=electronics&page=0&size=2","category=electronics&page=1&size=2","category=electronics&page=0&size=3"};var a=search(qs[0]);content(a,110L,103L);var b=search(qs[1]);content(b,104L,101L);var c=search(qs[2]);content(c,110L,103L,104L);calls(3);assertThat(search(qs[0])).isEqualTo(a);assertThat(search(qs[1])).isEqualTo(b);assertThat(search(qs[2])).isEqualTo(c);calls(3); }
 @Test @DisplayName("Search term cache separation") void a2_17() throws Exception { var a=search("category=electronics&q=mouse&size=50");content(a,103L,104L);var b=search("category=electronics&q=keyboard&size=50");content(b,101L,102L);calls(2);assertThat(search("category=electronics&q=mouse&size=50")).isEqualTo(a);assertThat(search("category=electronics&q=keyboard&size=50")).isEqualTo(b);calls(2); }
 @Test @DisplayName("Stock cache separation") void a2_18() throws Exception { content(search("category=electronics&size=50"),110L,103L,104L,101L,102L);content(search("category=electronics&size=50&inStock=true"),110L,103L,104L,101L);content(search("category=electronics&size=50&inStock=false"),102L);calls(3); }
 @Test @DisplayName("Sort cache separation") void a2_19() throws Exception { var a=search("category=electronics&size=50&sort=priceAsc");content(a,110L,103L,104L,101L,102L);var b=search("category=electronics&size=50&sort=priceDesc");content(b,102L,101L,103L,104L,110L);var c=search("category=electronics&size=50&sort=nameAsc");content(c,101L,102L,104L,110L,103L);calls(3);assertThat(search("category=electronics&size=50&sort=priceAsc")).isEqualTo(a);assertThat(search("category=electronics&size=50&sort=priceDesc")).isEqualTo(b);assertThat(search("category=electronics&size=50&sort=nameAsc")).isEqualTo(c);calls(3); }
 @Test @DisplayName("Price bound cache separation") void a2_20() throws Exception { var a=search("size=50&minPrice=1000&maxPrice=5000");content(a,110L,103L,104L,101L,111L);content(search("size=50&minPrice=2500&maxPrice=5000"),103L,104L,101L,111L);content(search("size=50&minPrice=2500&maxPrice=9000"),103L,104L,101L,111L,102L);calls(3);assertThat(search("size=50&minPrice=1000&maxPrice=5000")).isEqualTo(a);calls(3); }
 @Test @DisplayName("Equivalent requests share entries") void a2_21() throws Exception { var a=search("q= MOUSE &category= ELECTRONICS ");content(a,103L,104L);assertThat(search("sort=priceAsc&size=5&page=0&category=electronics&q=mouse")).isEqualTo(a);calls(1);reset();var b=search("");assertThat(search("q= &category= &page=0&size=5&sort=priceAsc")).isEqualTo(b);calls(1); }
 @Test @DisplayName("Exact expiry without sliding reads") void a2_22() throws Exception { var a=search("category=electronics&size=50");content(a,110L,103L,104L,101L,102L);calls(1);clock.advance(59);assertThat(search("category=electronics&size=50")).isEqualTo(a);calls(1);clock.advance(1);assertThat(search("category=electronics&size=50")).isEqualTo(a);calls(2); }
 @Test @DisplayName("Exact namespace invalidation") void a2_23() throws Exception { search("category=electronics&size=50");var keys=List.of("products:search:v1:synthetic","products:detail:103","products:search:v10:keep","orders:search:v1:keep","xproducts:search:v1:keep");for(String k:keys)cache.put(k,"sentinel",java.time.Duration.ofHours(1));ok("PUT","/api/products/103",update(),200);assertThat(cache.keys()).noneMatch(k->k.startsWith("products:search:v1:"));for(String k:keys.subList(1,keys.size()))assertThat(cache.get(k)).contains("sentinel"); }
 @Test @DisplayName("Last and very distant pages") void a2_24() throws Exception { var a=search("category=electronics&page=2&size=2");content(a,102L);metadata(a,2,2,5,3,false,true);cacheReset();var b=search("category=electronics&page=1000000&size=50");content(b);metadata(b,1000000,50,5,1,false,true);cacheReset();var c=search("category=electronics&page=0&size=50");content(c,110L,103L,104L,101L,102L);metadata(c,0,50,5,1,true,true); }
 @Test @DisplayName("Literal search and strict write boundaries") void a2_25() throws Exception { for(String q:List.of("%","_")){cacheReset();content(search("q="+q));}jdbc.update("insert into products(id,category,name,price_cents,sku,stock) values (113,'accessories','100%_ Cover',800,'CV-01',1)");for(String q:List.of("%","_")){cacheReset();content(search("q="+q),113L);}var bad=new ArrayList<ObjectNode>();for(String f:List.of("name","category","priceCents","stock")){var b=update();b.remove(f);bad.add(b);bad.add(update().putNull(f));}bad.addAll(List.of(update().put("name"," "),update().put("category"," "),update().put("name","x".repeat(101)),update().put("category","x".repeat(41)),update().put("category","bad_category"),update().put("priceCents",-1),update().put("stock",1000001),update().put("priceCents",1.5),update().put("stock",1.5)));for(var b:bad){reset();var before=snapshot();error("PUT","/api/products/103",b,400,"INVALID_REQUEST");assertThat(snapshot()).isEqualTo(before);} }
}
